### ISSUE TITLE
Use Docker-Based Travis Builds

### ISSUE THREAD

**Issue by kevinkreiser** [kevinkreiser/prime_server#27]
So many advantages but a few small catches. For one we'd need to change the install of various packages to something like: 

http://docs.travis-ci.com/user/migrating-from-legacy/?utm_source=legacy-notice&utm_medium=banner&utm_campaign=legacy-upgrade#How-do-I-install-APT-sources-and-packages%3F

We'd need to install libzmq into a non standard directory and add that to our paths, also no problem.

The only issue would be forcing the use of the compiler without using update alternatives, or maybe you can update alternatives for just one user? Seems to be the only issue left to tackle

**Comment by TeXitoi** [comment]
If that's the only issue, you can just
```yml
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - g++-4.9
install:
  - export CC=gcc-4.9 CXX=g++-4.9
```
in your `.travis`. `./configure` will use that.

I have almost compiled prime_server with `sudo: false` except from zmq on https://github.com/TeXitoi/valhalla-compile
